def cipher(text, shift, encrypt=True):
    """
    Encrypts a given input alphabetical text string.

    Parameters
    ----------
    text : str
      This is the input text data sent to be ciphered (should be English).

    shift : int
      This is the ficed number that each letter is replaced by a letter some fixed number of positions down the alphabet. 
      It can be any integers, both positive and negative.

    encrypt : bool
      If encrypt is True (default value), each alphabet character will be replaced by another alphabet character;
      the extent of this shift will be dependent on the shift parameter.

      If encrypt is False, a similar process will happen, and the extent is also dependent on shift.
      However, when encrypt is False, it also enables decryption, if some output generated by the cipher function is
      re-entered as input into the cipher function.


    Returns
    -------
    str
      The string after ciphered is the output.

    Examples
    --------
    >>> from cipher_tz2372 import cipher_tz2372
    >>> cipher_tz2372.cipher('abc', 1) #encrypt is True by default
    'bcd'

    >>> from cipher_tz2372 import cipher_tz2372
    >>> cipher_tz2372.cipher('bcd', -1) #encrypt is True by default
    'abc'
    """

    alphabet = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    new_text = ''
    for c in text:
        index = alphabet.find(c)
        if index == -1:
            new_text += c
        else:
            new_index = index + shift if encrypt == True else index - shift
            new_index %= len(alphabet)
            new_text += alphabet[new_index:new_index+1]
    return new_text